/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serial;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.Timer;
import javax.swing.text.Document;

/**
 *
 * @author ALUNO
 */
public class Principal extends javax.swing.JFrame {
    Port sport = new Port();
    boolean conectado = false;
    boolean atualizacao = true;
    Timer timer = new Timer(1000, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
                temperatura();
            }
        });
        
    /**
     * Creates new form Principal
     */
    public Principal(){
        initComponents();
        spporta.setValue(4);
        txtlcdl1.setDocument(new DocumentoLimitado(16));
        txtlcdl2.setDocument(new DocumentoLimitado(16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_portd = new javax.swing.JLabel();
        rb_d0 = new javax.swing.JRadioButton();
        rb_d1 = new javax.swing.JRadioButton();
        rb_d2 = new javax.swing.JRadioButton();
        rb_d3 = new javax.swing.JRadioButton();
        rb_d4 = new javax.swing.JRadioButton();
        rb_d5 = new javax.swing.JRadioButton();
        rb_d6 = new javax.swing.JRadioButton();
        rb_d7 = new javax.swing.JRadioButton();
        bt_dlt = new javax.swing.JButton();
        bt_ddt = new javax.swing.JButton();
        bt_bdt = new javax.swing.JButton();
        bt_blt = new javax.swing.JButton();
        rb_b7 = new javax.swing.JRadioButton();
        rb_b6 = new javax.swing.JRadioButton();
        rb_b5 = new javax.swing.JRadioButton();
        rb_b3 = new javax.swing.JRadioButton();
        rb_b4 = new javax.swing.JRadioButton();
        rb_b2 = new javax.swing.JRadioButton();
        rb_b1 = new javax.swing.JRadioButton();
        rb_b0 = new javax.swing.JRadioButton();
        lbl_portb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        progressc = new javax.swing.JProgressBar();
        lblsliderc = new javax.swing.JLabel();
        sliderc = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        spporta = new javax.swing.JSpinner();
        COM = new javax.swing.JLabel();
        btconecdesc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        progresst = new javax.swing.JProgressBar();
        lbltemperatura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rb_c5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtlcdl2 = new javax.swing.JTextField();
        txtlcdl1 = new javax.swing.JTextField();
        rb_atualizacao = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Porta Serial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LED's"));

        lbl_portd.setText("PORTD");

        rb_d0.setText("D0");
        rb_d0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_d0StateChanged(evt);
            }
        });
        rb_d0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d0ActionPerformed(evt);
            }
        });

        rb_d1.setText("D1");
        rb_d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d1ActionPerformed(evt);
            }
        });

        rb_d2.setText("D2");
        rb_d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d2ActionPerformed(evt);
            }
        });

        rb_d3.setText("D3");
        rb_d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d3ActionPerformed(evt);
            }
        });

        rb_d4.setText("D4");
        rb_d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d4ActionPerformed(evt);
            }
        });

        rb_d5.setText("D5");
        rb_d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d5ActionPerformed(evt);
            }
        });

        rb_d6.setText("D6");
        rb_d6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d6ActionPerformed(evt);
            }
        });

        rb_d7.setText("D7");
        rb_d7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_d7ActionPerformed(evt);
            }
        });

        bt_dlt.setText("Liga T");
        bt_dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dltActionPerformed(evt);
            }
        });

        bt_ddt.setText("Desliga T");
        bt_ddt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ddtActionPerformed(evt);
            }
        });

        bt_bdt.setText("Desliga T");
        bt_bdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bdtActionPerformed(evt);
            }
        });

        bt_blt.setText("Liga T");
        bt_blt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bltActionPerformed(evt);
            }
        });

        rb_b7.setText("B7");
        rb_b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b7ActionPerformed(evt);
            }
        });

        rb_b6.setText("B6");
        rb_b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b6ActionPerformed(evt);
            }
        });

        rb_b5.setText("B5");
        rb_b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b5ActionPerformed(evt);
            }
        });

        rb_b3.setText("B3");
        rb_b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b3ActionPerformed(evt);
            }
        });

        rb_b4.setText("B4");
        rb_b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b4ActionPerformed(evt);
            }
        });

        rb_b2.setText("B2");
        rb_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b2ActionPerformed(evt);
            }
        });

        rb_b1.setText("B1");
        rb_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b1ActionPerformed(evt);
            }
        });

        rb_b0.setText("B0");
        rb_b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_b0ActionPerformed(evt);
            }
        });

        lbl_portb.setText("PORTB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb_d7)
                        .addComponent(rb_d6)
                        .addComponent(rb_d5)
                        .addComponent(rb_d4)
                        .addComponent(rb_d3)
                        .addComponent(rb_d2)
                        .addComponent(rb_d1)
                        .addComponent(rb_d0)
                        .addComponent(lbl_portd))
                    .addComponent(bt_dlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_ddt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_portb)
                    .addComponent(rb_b2)
                    .addComponent(rb_b1)
                    .addComponent(rb_b0)
                    .addComponent(rb_b3)
                    .addComponent(rb_b5)
                    .addComponent(rb_b4)
                    .addComponent(rb_b6)
                    .addComponent(rb_b7)
                    .addComponent(bt_blt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_bdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_portd)
                    .addComponent(lbl_portb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_d0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_d1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_d2)
                                    .addComponent(rb_b2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_b0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_b1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_d3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_d4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_d5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_d6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_d7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_b3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_b4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_b5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_b6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_b7)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_dlt)
                    .addComponent(bt_blt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ddt)
                    .addComponent(bt_bdt))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cooler"));

        progressc.setMaximum(255);

        lblsliderc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblsliderc.setText("0V");

        sliderc.setMaximum(255);
        sliderc.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderc.setToolTipText("");
        sliderc.setValue(0);
        sliderc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slidercStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblsliderc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(progressc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsliderc))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração"));

        COM.setText("COM");

        btconecdesc.setText("Conectar");
        btconecdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconecdescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(COM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spporta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btconecdesc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btconecdesc)
                    .addComponent(COM)
                    .addComponent(spporta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura / Aquecedor"));

        progresst.setMaximum(127);

        lbltemperatura.setText("Temperatura");

        jLabel1.setText("Temperatura de 0 a 127C");

        rb_c5.setText("C5");
        rb_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_c5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Aquecedor");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(rb_c5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progresst, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbltemperatura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbltemperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progresst, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_c5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("LCD"));

        txtlcdl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlcdl2KeyReleased(evt);
            }
        });

        txtlcdl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlcdl1KeyReleased(evt);
            }
        });

        rb_atualizacao.setSelected(true);
        rb_atualizacao.setText("Atualização automatica");
        rb_atualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_atualizacaoActionPerformed(evt);
            }
        });

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlcdl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlcdl2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_atualizacao))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtlcdl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlcdl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_atualizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel3.setText("                                                                                                                  Plataforma de comunicação serial com Picsimlab V0.6.");

        jLabel4.setText("Board 4, PIC18f4550.");

        jLabel5.setText("30/06/2017   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_d0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d0ActionPerformed
        onoffpinos(rb_d0);
    }//GEN-LAST:event_rb_d0ActionPerformed

    private void rb_b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b6ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_b6);
    }//GEN-LAST:event_rb_b6ActionPerformed

    private void rb_b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b3ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_b3);
    }//GEN-LAST:event_rb_b3ActionPerformed

    private void rb_d7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d7ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_d7);
    }//GEN-LAST:event_rb_d7ActionPerformed

    private void bt_dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dltActionPerformed
        rb_d0.getModel().setSelected(true);
        rb_d1.getModel().setSelected(true);
        rb_d2.getModel().setSelected(true);
        rb_d3.getModel().setSelected(true);
        rb_d4.getModel().setSelected(true);
        rb_d5.getModel().setSelected(true);
        rb_d6.getModel().setSelected(true);
        rb_d7.getModel().setSelected(true);
        try {
            sport.write("1");
            Thread.sleep(80);
            sport.write("D");
            Thread.sleep(80);
            sport.write("t");
            Thread.sleep(80);
            } catch (Exception e) {
                System.err.println("Error: Write port failed: " + e);
        }
        
    }//GEN-LAST:event_bt_dltActionPerformed

    private void bt_ddtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ddtActionPerformed
        rb_d0.getModel().setSelected(false);
        rb_d1.getModel().setSelected(false);
        rb_d2.getModel().setSelected(false);
        rb_d3.getModel().setSelected(false);
        rb_d4.getModel().setSelected(false);
        rb_d5.getModel().setSelected(false);
        rb_d6.getModel().setSelected(false);
        rb_d7.getModel().setSelected(false);
        try {
            sport.write("0");
            Thread.sleep(80);
            sport.write("D");
            Thread.sleep(80);
            sport.write("t");
            Thread.sleep(80);
            } catch (Exception e) {
                System.err.println("Error: Write port failed: " + e);
        }
    }//GEN-LAST:event_bt_ddtActionPerformed

    private void bt_bdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bdtActionPerformed
        rb_b0.getModel().setSelected(false);
        rb_b1.getModel().setSelected(false);
        rb_b2.getModel().setSelected(false);
        rb_b3.getModel().setSelected(false);
        rb_b4.getModel().setSelected(false);
        rb_b5.getModel().setSelected(false);
        rb_b6.getModel().setSelected(false);
        rb_b7.getModel().setSelected(false);
        try {
            sport.write("0");
            Thread.sleep(80);
            sport.write("B");
            Thread.sleep(80);
            sport.write("t");
            Thread.sleep(80);
            } catch (Exception e) {
                System.err.println("Error: Write port failed: " + e);
        }
    }//GEN-LAST:event_bt_bdtActionPerformed

    private void bt_bltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bltActionPerformed
        rb_b0.getModel().setSelected(true);
        rb_b1.getModel().setSelected(true);
        rb_b2.getModel().setSelected(true);
        rb_b3.getModel().setSelected(true);
        rb_b4.getModel().setSelected(true);
        rb_b5.getModel().setSelected(true);
        rb_b6.getModel().setSelected(true);
        rb_b7.getModel().setSelected(true);  
        try {
            sport.write("1");
            Thread.sleep(80);
            sport.write("B");
            Thread.sleep(80);
            sport.write("t");
            Thread.sleep(80);
            } catch (Exception e) {
                System.err.println("Error: Write port failed: " + e);
        }
    }//GEN-LAST:event_bt_bltActionPerformed

    private void rb_d0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_d0StateChanged

    }//GEN-LAST:event_rb_d0StateChanged

    private void btconecdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconecdescActionPerformed

        if(conectado == false){
            try {
              sport.open("COM"+spporta.getValue());
              conectado = true;
              btconecdesc.setText("Desconectar");
              timer.start();
              
            } catch (Exception e) {
              System.err.println("Error: open port failed: " + e);
            }
        }else if(conectado == true){
            try {
              sport.close();
              conectado = false;
              btconecdesc.setText("Conectar");
              timer.stop();
              rb_b0.getModel().setSelected(false);
              rb_b1.getModel().setSelected(false);
              rb_b2.getModel().setSelected(false);
              rb_b3.getModel().setSelected(false);
              rb_b4.getModel().setSelected(false);
              rb_b5.getModel().setSelected(false);
              rb_b6.getModel().setSelected(false);
              rb_b7.getModel().setSelected(false);
              rb_d0.getModel().setSelected(false);
              rb_d1.getModel().setSelected(false);
              rb_d2.getModel().setSelected(false);
              rb_d3.getModel().setSelected(false);
              rb_d4.getModel().setSelected(false);
              rb_d5.getModel().setSelected(false);
              rb_d6.getModel().setSelected(false);
              rb_d7.getModel().setSelected(false);
              rb_c5.getModel().setSelected(false);
              lbltemperatura.setText("Temperatura");
              progresst.getModel().setValue(0);
              sliderc.getModel().setValue(0);
              progressc.getModel().setValue(0);
              txtlcdl1.setText("");
              txtlcdl2.setText("");
            } catch (Exception e) {
              System.err.println("Error: open port failed: " + e);
            }
        }
    }//GEN-LAST:event_btconecdescActionPerformed

    private void rb_b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b0ActionPerformed
        onoffpinos(rb_b0);
    }//GEN-LAST:event_rb_b0ActionPerformed

    private void rb_d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d1ActionPerformed
        onoffpinos(rb_d1);
    }//GEN-LAST:event_rb_d1ActionPerformed

    private void rb_d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d2ActionPerformed
        onoffpinos(rb_d2);
    }//GEN-LAST:event_rb_d2ActionPerformed

    private void rb_d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d3ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_d3);
    }//GEN-LAST:event_rb_d3ActionPerformed

    private void rb_d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d4ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_d4);
    }//GEN-LAST:event_rb_d4ActionPerformed

    private void rb_d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d5ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_d5);
    }//GEN-LAST:event_rb_d5ActionPerformed

    private void rb_d6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_d6ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_d6);
    }//GEN-LAST:event_rb_d6ActionPerformed

    private void rb_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b1ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_b1);
    }//GEN-LAST:event_rb_b1ActionPerformed

    private void rb_b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b2ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_b2);
    }//GEN-LAST:event_rb_b2ActionPerformed

    private void rb_b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b4ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_b4);
    }//GEN-LAST:event_rb_b4ActionPerformed

    private void rb_b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b5ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_b5);
    }//GEN-LAST:event_rb_b5ActionPerformed

    private void rb_b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_b7ActionPerformed
        // TODO add your handling code here:
        onoffpinos(rb_b7);
    }//GEN-LAST:event_rb_b7ActionPerformed

    private void slidercStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidercStateChanged
        slidev();
    }//GEN-LAST:event_slidercStateChanged

    private void rb_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_c5ActionPerformed
        onoffpinos(rb_c5);
    }//GEN-LAST:event_rb_c5ActionPerformed

    private void txtlcdl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlcdl1KeyReleased
        if(atualizacao == true)
            lcd('1');
    }//GEN-LAST:event_txtlcdl1KeyReleased

    private void txtlcdl2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlcdl2KeyReleased
        if(atualizacao == true)
            lcd('2');
    }//GEN-LAST:event_txtlcdl2KeyReleased

    private void rb_atualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_atualizacaoActionPerformed
        if(rb_atualizacao.getModel().isSelected()==true){
            atualizacao = true;
        }else{
            atualizacao = false;
        }
    }//GEN-LAST:event_rb_atualizacaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lcd('1');
        lcd('2');
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COM;
    private javax.swing.JButton bt_bdt;
    private javax.swing.JButton bt_blt;
    private javax.swing.JButton bt_ddt;
    private javax.swing.JButton bt_dlt;
    private javax.swing.JButton btconecdesc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_portb;
    private javax.swing.JLabel lbl_portd;
    private javax.swing.JLabel lblsliderc;
    private javax.swing.JLabel lbltemperatura;
    private javax.swing.JProgressBar progressc;
    private javax.swing.JProgressBar progresst;
    private javax.swing.JRadioButton rb_atualizacao;
    private javax.swing.JRadioButton rb_b0;
    private javax.swing.JRadioButton rb_b1;
    private javax.swing.JRadioButton rb_b2;
    private javax.swing.JRadioButton rb_b3;
    private javax.swing.JRadioButton rb_b4;
    private javax.swing.JRadioButton rb_b5;
    private javax.swing.JRadioButton rb_b6;
    private javax.swing.JRadioButton rb_b7;
    private javax.swing.JRadioButton rb_c5;
    private javax.swing.JRadioButton rb_d0;
    private javax.swing.JRadioButton rb_d1;
    private javax.swing.JRadioButton rb_d2;
    private javax.swing.JRadioButton rb_d3;
    private javax.swing.JRadioButton rb_d4;
    private javax.swing.JRadioButton rb_d5;
    private javax.swing.JRadioButton rb_d6;
    private javax.swing.JRadioButton rb_d7;
    private javax.swing.JSlider sliderc;
    private javax.swing.JSpinner spporta;
    private javax.swing.JTextField txtlcdl1;
    private javax.swing.JTextField txtlcdl2;
    // End of variables declaration//GEN-END:variables
    private void lcd(char linha){
        int i;
        if(linha == '1'){
            try {
                sport.write('l');
                Thread.sleep(50);
                sport.write('1');
                Thread.sleep(50);
                for(i=0 ;i<txtlcdl1.getText().length();i++){
                    sport.write(txtlcdl1.getText().charAt(i));
                    Thread.sleep(50);
                }
                for(i=txtlcdl1.getText().length();i<16;i++){
                    sport.write(' ');
                    Thread.sleep(50);
                }
            } catch (Exception e) {
                  System.err.println("Error: Write port failed: " + e);
            }
        }else if(linha == '2'){
            try {
                sport.write('l');
                Thread.sleep(50);
                sport.write('2');
                Thread.sleep(50);
                for(i=0 ;i<txtlcdl2.getText().length();i++){
                    sport.write(txtlcdl2.getText().charAt(i));
                    Thread.sleep(50);
                }
                for(i=txtlcdl2.getText().length();i<16;i++){
                    sport.write(' ');
                    Thread.sleep(50);
                }
            } catch (Exception e) {
                  System.err.println("Error: Write port failed: " + e);
            }
        }
    }
    private void onoffpinos(JRadioButton rb){
        if(rb.getModel().isSelected()==true){
            try {
                sport.write('1');
                Thread.sleep(80);
                sport.write(rb.getText().charAt(0));
                Thread.sleep(80);
                sport.write(rb.getText().charAt(1));
                Thread.sleep(80);
            } catch (Exception e) {
                System.err.println("Error: Write port failed: " + e);
            }
        }else{
            try {
                sport.write('0');
                Thread.sleep(80);
                sport.write(rb.getText().charAt(0));
                Thread.sleep(80);
                sport.write(rb.getText().charAt(1));
                Thread.sleep(80);
            } catch (Exception e) {
                System.err.println("Error: Write port failed: " + e);
            }
        }
    }
    private void temperatura(){
        char temp;
        try {
            sport.write('t');
            temp = sport.read();
            lbltemperatura.setText(String.valueOf((int)temp)+"C   "+String.valueOf((int)100*temp/127)+"%");
            progresst.getModel().setValue((int)temp);
        } catch (Exception e) {
            System.err.println("Error: Write port failed: " + e);
        }
    }
    private void slidev(){
        if(conectado == true){
        int i,value = sliderc.getValue();
        float volts = ((float)value/255)*50000;
        String voltss = String.valueOf(volts/10000);
        for(i = 0; i<6 ; i++){
            if(voltss.length()==i){
                break;
            }
        }
        
        int valuel =0;
        int valueh = 0;
        if (value<=127){
            valuel = value;
        }else if(value > 127){
            valueh = value -127;
            valuel = 127;
        }
        if(value == 255){
            valueh = valueh-1;
        }
        try {
            sport.write('c');
            Thread.sleep(50);
            sport.write(valueh);
            Thread.sleep(50);
            sport.write(valuel);
            Thread.sleep(50);
            
            lblsliderc.setText(String.valueOf(value*100/255)+"%       "+String.valueOf(volts/10000).substring(0,i)+'V');
            progressc.getModel().setValue(value);
        } catch (Exception e) {
              System.err.println("Error: Write port failed: " + e);
        }
    }
    }
}
